version: '3.7'

services:

  playground-dashboard:
    container_name: playground-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3002:80'